/**
 * Shared TypeScript interfaces for the Asha Mental Wellness Tracker.
 * Centralizes all domain models to eliminate duplicate definitions
 * and enforce strict type safety across components and API routes.
 */

/** A single mood/stress log entry from journal analysis. */
export interface MoodLog {
  date: string;
  stressScore: number;
  emotion: string;
}

/** The structured result returned by the /api/wellness GenAI analysis. */
export interface AnalysisResult {
  stressScore: number;
  primaryEmotion: string;
  triggers: string[];
  copingStrategies: string[];
  encouragement: string;
}

/** A single message in the Asha chat conversation. */
export interface ChatMessage {
  role: "user" | "model";
  content: string;
}

/** Form data collected during the AI Coach onboarding wizard. */
export interface CoachFormData {
  prepType: string;
  targetGoal: string;
  skillLevel: string;
  targetDate: string;
  hoursPerDay: string;
  strengths: string;
  weaknesses: string;
  notes: string;
}

/** Daily time-budget splits generated by the AI Coach. */
export interface DailyRoutineSplits {
  studyHours: number;
  breakHours: number;
  mindfulnessMinutes: number;
  outline: string[];
}

/** A single week in the AI Coach study roadmap. */
export interface WeeklySchedule {
  week: string;
  milestones: string[];
  wellnessFocus?: string;
}

/** The full AI Coach roadmap plan returned by /api/coach. */
export interface CoachPlan {
  coachTitle: string;
  summary: string;
  weeklySchedule: WeeklySchedule[];
  strengthMaximizer?: string;
  weaknessMitigation?: string;
  dailyRoutineSplits: DailyRoutineSplits;
}
